# Generated by Django 4.2.7 on 2023-11-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='choice',
            new_name='type',
        ),
    ]
